Feature/try archive
ufcg-lsd/saps-archiver pull request #23
Opened 2023-05-22 18:50 UTC by bernardoezequias

2023-05-24 17:22 UTC, thiagomanel requested changes
many comments but I need tests before accepting the PR

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +//TODO: missing imports
could we remove this TODO?

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +        FileInputStream input = new FileInputStream([0]);
`[0]`? nao deveria ser `args[0]`

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +        Archiver fetcher = createArchiver(properties);
archiver or fetcher?

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +            Thread.sleep(fetcher.getDelayMilis());
it is odd to have this getDelayMilis. maybe, this config should be read here in the main

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +        Archiver archiver = new DefaultArchiver(properties, catalog, permanentStorage);
there is no need to declare this archiver variable here

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +        throw new SapsException("Failed to recognize type of permanent storage");
this line 30 seems wrong

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +//TODO imports missing
could we remove this TODO?

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +    	throw new WrongConfigurationException("Error on validate the file. Missing properties for start Saps Controller.");
I think there is already a java sdk exception to this

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +      } deleteTempData(task);
put the delete call (line 51) in line 52

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/ArchiverMain.java
> +package saps.archiver.core;
check code identation i

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +      SapsPropertiesConstants.SAPS_PERMANENT_STORAGE_TYPE
are we using all these constants?

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +    if (taskDir.exists() && taskDir.isDirectory()) {
maybe remove this call to a std java method?

2023-05-24 17:22 UTC, thiagomanel commented on src/main/java/saps/archiver/core/DefaultArchiver.java
> +   * It returns the maximum value between garbage collector and archiver delay constants
this method shoudl be removed

2023-06-14 17:55 UTC, thiagomanel requested changes
I need to be able to run the test in the command line `mvn test`
also, I think the `pom.xml` has many unused dependencies. please, check this and remove any unused dependency

2023-06-14 19:38 UTC, bernardoezequias commented
> I need to be able to run the test in the command line `mvn test` also, I think the `pom.xml` has many unused dependencies. please, check this and remove any unused dependency

done

2023-06-28 16:49 UTC, thiagomanel approved these changes
lgtm

2023-06-29 12:26 UTC, jhenriqueax approved these changes

2023-06-29 12:36 UTC, merged